### ISSUE TITLE
Provide command line arguments for Revit TestAdapter

### ISSUE THREAD

**Issue by SoggyBottomBoy** [ricaun-io/RevitTest#10]
Hi I am trying to use the test adapter but I don't have a license for Revit and would like to be able to use the command line argument `/viewer` when opening Revit.

I also get the exception `TestExecuteUtils.Execute is null` when running some tests that have no reliance on the revit instance. Is there any chance that the TestAdapter could be open sourced so that I can debug these issues?

**Comment by ricaun** [comment]
> Hi I am trying to use the test adapter but I don't have a license for Revit and would like to be able to use the command line argument `/viewer` when opening Revit.
> 
If you run with `/viewer` you don't need a license, really? Interesting to know.

Is kinda possible to inject some extra command using the Language option.
```c#
[assembly: System.Reflection.AssemblyMetadata("NUnit.Language", "ENU /viewer")]
```
You can try but TestAdapter was not designed to work in the viewer.

> I also get the exception TestExecuteUtils.Execute is null when running some tests that have no reliance on the revit instance. Is there any chance that the TestAdapter could be open sourced so that I can debug these issues?
By default the `RevitTest.TestAdater` gonna run the test assembly inside Revit, and does not matter if you have Revit reference or not. At the moment the project is private.

**Comment by ricaun** [comment]
What test are you running the get the `TestExecuteUtils.Execute is null`?

If you click in the `RevitTest` button there is a basic log in there.

![image](https://github.com/ricaun-io/RevitTest/assets/12437519/6deec9f2-3b4a-4529-bb10-70230885ce6b)

**Comment by ricaun** [comment]
> Hi I am trying to use the test adapter but I don't have a license for Revit and would like to be able to use the command line argument `/viewer` when opening Revit.
> 
> I also get the exception `TestExecuteUtils.Execute is null` when running some tests that have no reliance on the revit instance. Is there any chance that the TestAdapter could be open sourced so that I can debug these issues?

I gonna close this issue, if you still have problem with the `TestExecuteUtils.Execute is null` please update to the last version.
The last version is `1.4.1` at the moment.

Now the version 1.4.* have a handy support when Revit open with the `Viewer Mode`, now the dialog box that show `Viewer Mode` is close by default.
