### ISSUE TITLE
Addin Id | Which Addin Context is the Test run in? 

### ISSUE THREAD

**Issue by tnmarch** [ricaun-io/RevitTest#11]
I've run into an issue with enabling/disabling updaters. When I run code that normally works in my addin that enables/disables and updater, all works fine. But when I run the same code in a test, I get thrown the error "Updater does not belong to the current Addin" or however its worded. 

I haven't been able to prove this out, but my guess is that the test itself is running under a different Addin Id than my Addin, so when disable/enable are called, the current addin is the testing addin, not my adding. 

I was thinking of doing something along the lines of swapping out Addin Ids when the Updaters are initialized when I'm in a testing environment, but I don't have access to your addin Id to even give that a shot.  

Have you run into this issue? Is my guess to the issue correct? Any suggestions on how to work through this? 

Thank you! Love the work you're doing with this.

**Comment by ricaun** [comment]
Hello Tristan,

All the tests runs using the `ricaun.RevitTest.Application` addin, if you execute some test like this you can find the guid of the application.

```C#
[Test]
public void RevitTests_ActiveAddInId(Application application)
{
    Assert.IsNotNull(application);
    Console.WriteLine(application.ActiveAddInId.GetAddInName());
    Console.WriteLine(application.ActiveAddInId.GetGUID());
}
```

In your case I don't know if is possible to change the `AddInId` after you register the updater, I guess the `AddInId` is lock with the id of the updater when you register in Revit.

I usually create a different updater guid for the test, and using the default `ActiveAddInId` to register the updater, run the updater tests and unregistered in the end. This gonna make the `ricaun.RevitTest.Application` to have ownership of the test allowing enable/disable.

And looks like you are trying to enable/disable an already created updater from another AddIn, Revit does not allow that so is better to create one inside the test with a random guid.

**Comment by ricardosalasv** [comment]
Hello Luiz,

I am reading this with a similar doubt. My case is that I want to check the visibility of some pushbuttons after having performed some modifications on them in the ribbon with my plugin.

As I now understand that the TestAdapter works through your AddIn, that does mean that it cannot access information or modifications made to the UI from another plugin, as I am getting a InvalidOperationException each time I try, for example, RibbonPanel.GetItems(); if that is the case it makes sense to me now.

Apart from that, great work with this project, it has been very useful!

**Comment by ricaun** [comment]
> As I now understand that the TestAdapter works through your AddIn, that does mean that it cannot access information or modifications made to the UI from another plugin, as I am getting a InvalidOperationException each time I try, for example, RibbonPanel.GetItems(); if that is the case it makes sense to me now.

I guess is hard/complex to access some info from a loaded Addin, first you need to guarantee that the addin is loaded when you run the test, and you need to find that `IExternalApplication` loaded in Revit.

```C#
[Test]
public void RevitTests_Applications(UIApplication uiapp)
{
    foreach (IExternalApplication loadedApplication in uiapp.LoadedApplications)
    {
        Console.WriteLine(loadedApplication);
        if (loadedApplication is YourApp app)
        {
            _ = app.RibbonPanel;
        }
    }
}
```

This would find all the `IExternalApplication` loaded in Revit and if is the same class as `YourApp` you found your loaded addin `IExternalApplication` with all the content inside.

**Comment by ricardosalasv** [comment]
Correct, and also I guess as my AddIn has a different VendorId I could not access to perform actions or queries on the IExternalApplication or the UIControlledApplication of my AddIn.

Thanks for the code snippet you shared, it could actually guide me through some interesting places!

**Comment by ricaun** [comment]
> Correct, and also I guess as my AddIn has a different VendorId I could not access to perform actions or queries on the IExternalApplication or the UIControlledApplication of my AddIn.

Yes the VendorId is different, it all gonna depend what you want to access in the existent IExternalApplication. If depends from the ActiveAddinId like IUpdate and Storage, gonna be easier to make the unit test to create new one instead of trying to access the exist inside Revit.

**Comment by tnmarch** [comment]
So just to clarify the overall meaning of this, which makes sense to me, everything that is run through RevitTest is run under the RevitTest addin, NOT the addin we are developing (even if we have it loaded in). RevitTest and our addin will reference the same .dll loaded into the AppDomain, but the addin running the code is different. 

So things like AddinIds, VendorIds, etc. won't function as we expect since the code is being run by a different addin than we configure.  

This all makes sense to me, just want to make sure I understand completely how this is running. This same issue with the UpdaterId has happened with another testing framework as well, due to (what I am making sure here) both the Testing addin and My addin being loaded referencing the same Updater.
